image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java "-Dspring.datasource.url=jdbc:mysql://185.119.57.176:3306/app" -jar ./artifacts/aqa-shop/aqa-shop.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true  # запускаем тест, флаг --info позволяет выводить больше информации